elesis-AAAAAA/Z01.1-AAAAAAAAAAAA

INTEGRANTES.json
=> Me adicionar ao integrantes.json

.gitignore, Projetos/B-LogicaCombinacional/src/And16.vhd
=> and16way implemented

Projetos/B-LogicaCombinacional/src/Mux2Way.vhd
=> Mux2Way implemented

Projetos/B-LogicaCombinacional/src/DMux2Way.vhd
=> dmux2way implemented

Projetos/B-LogicaCombinacional/src/Nor8Way.vhd
=> Nor8Way implemented

.gitignore, Projetos/B-LogicaCombinacional/src/DMux4Way.vhd
=> dmux 4 way implemented

Projetos/B-LogicaCombinacional/src/BarrelShifter16.vhd
=> BarrelShifter16 implemented

Projetos/B-LogicaCombinacional/src/Or16.vhd
=> or16 feito

Projetos/B-LogicaCombinacional/src/circuito.vhd
=> circuito implemented

Projetos/B-LogicaCombinacional/src/detectorDeMoedas.vhd
=> detectorDeMoedas implemented

Projetos/B-LogicaCombinacional/src/sevenSeg.vhd
=> Implemented sevenSeg

Projetos/B-LogicaCombinacional/src/Mux4Way16.vhd
=> mux4way16 feito

Projetos/C-UnidadeLogicaAritmetica/config_testes.txt, Projetos/C-UnidadeLogicaAritmetica/src/Add16.vhd
=> add16 implemented

Projetos/C-UnidadeLogicaAritmetica/config_testes.txt, Projetos/C-UnidadeLogicaAritmetica/src/zerador16.vhd
=> zerador16 implemented

Projetos/C-UnidadeLogicaAritmetica/src/ALU.vhd
=> Implementa ALU

Projetos/C-UnidadeLogicaAritmetica/src/ALU.vhd, Projetos/C-UnidadeLogicaAritmetica/src/Mux4Way16.vhd, Projetos/C-UnidadeLogicaAritmetica/src/Xor16.vhd
=> Adicionando xor e shifter

Projetos/C-UnidadeLogicaAritmetica/Quartus/DE0_CV_Default.qsf, Projetos/C-UnidadeLogicaAritmetica/src/ALU.vhd, Projetos/C-UnidadeLogicaAritmetica/src/And16.vhd, Projetos/C-UnidadeLogicaAritmetica/src/Mux16.vhd, Projetos/C-UnidadeLogicaAritmetica/src/TopLevel.vhd, Projetos/C-UnidadeLogicaAritmetica/src/Xor16.vhd
- try fpga port map
- first implementation of ULA on FPGA
- b i n g o
=> feat/resultado ULA display

Projetos/D-LogicaSequencial/config_testes.txt, Projetos/D-LogicaSequencial/src/Ram64.vhd
=> Ram64 implemented

Projetos/D-LogicaSequencial/src/videos.md
=> Feat/video fpga ram8 e PC

Projetos/E-Assembly/config_testes.txt, Projetos/E-Assembly/src/SWeLED.nasm
=> SWeLED implemented

Projetos/E-Assembly/config_testes.txt, Projetos/E-Assembly/src/max.nasm
=> Max implemented

.github/CODEOWNERS, Projetos/E-Assembly/config_testes.txt, Projetos/E-Assembly/src/isEven.nasm
=> isEven implemented

Projetos/E-Assembly/config_testes.txt, Projetos/E-Assembly/src/abs.nasm
=> abs implemented

Projetos/E-Assembly/config_testes.txt, Projetos/E-Assembly/src/add.nasm
=> add funcionando

Projetos/E-Assembly/config_testes.txt, Projetos/E-Assembly/src/pow.nasm
=> pow implemented

Projetos/E-Assembly/config_testes.txt, Projetos/E-Assembly/src/mov.nasm
=> mov implemented

Projetos/E-Assembly/src/video_quadrado_lcd.txt
=> Video quadrado

.github/workflows/actions.yml, Projetos/F-Computador/src/CPU.vhd, Projetos/F-Computador/src/ControlUnit.vhd, Projetos/F-Computador/testes/tb_ControlUnit.vhd
=> Registrador S

.github/workflows/actions.yml, .gitignore, Projetos/G-Assembler/.gitignore, Projetos/G-Assembler/Assembler/src/main/java/assembler/SymbolTable.java
=> SymbolTable implemented
